#!/bin/sh

if [ $(pidof cutenews) ]
    then
        run-standalone.sh dbus-send --print-reply --dest=org.marxoft.cutenews /org/marxoft/cutenews org.marxoft.cutenews.showWindow
    else
        run-standalone.sh /opt/cutenews/bin/cutenews "--window"
fi
