#!/bin/sh

if [ $(pidof cutenews-client) ]
    then
        run-standalone.sh dbus-send --print-reply --dest=org.marxoft.cutenewsclient /org/marxoft/cutenewsclient org.marxoft.cutenewsclient.showWindow
    else
        run-standalone.sh /opt/cutenews-client/bin/cutenews-client "--window"
fi
