#!/bin/sh

set -e

subscriptions_file="/home/user/.config/cuteNews/eventfeedsubscriptions"

if [ -f "$subscriptions_file" ]
    then
        for id in $(cat "$subscriptions_file")
        do
            echo "Removing cuteNews events for subscription $id"
            /usr/bin/aegis-exec -s -u user dbus-send --print-reply --type=method_call --dest=com.nokia.home.EventFeed /eventfeed com.nokia.home.EventFeed.removeItemsBySourceName string:"cutenews$id"
        done
fi

exit 0
